"""partner upd

Revision ID: 4786ee9c3974
Revises: b9006fa1d79f
Create Date: 2025-06-08 17:08:47.478582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4786ee9c3974'
down_revision: Union[str, None] = 'b9006fa1d79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('last_partner', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('human_last_patner_fkey'), 'human', type_='foreignkey')
    op.create_foreign_key(None, 'human', 'human', ['last_partner'], ['id'])
    op.drop_column('human', 'last_patner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('last_patner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'human', type_='foreignkey')
    op.create_foreign_key(op.f('human_last_patner_fkey'), 'human', 'human', ['last_patner'], ['id'])
    op.drop_column('human', 'last_partner')
    # ### end Alembic commands ###
