"""test1

Revision ID: 6c9e2790f15b
Revises: cf38e5cbadec
Create Date: 2025-06-09 15:52:17.464002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9e2790f15b'
down_revision: Union[str, None] = 'cf38e5cbadec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('pregnancy', sa.Integer(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('last_partner', sa.Integer(), nullable=True),
    sa.Column('death_or_alive', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['human.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_partner'], ['human.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mother_id'], ['human.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human')
    # ### end Alembic commands ###
