"""partner

Revision ID: b9006fa1d79f
Revises: fccf943ad443
Create Date: 2025-06-08 17:02:22.536260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9006fa1d79f'
down_revision: Union[str, None] = 'fccf943ad443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('last_patner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'human', 'human', ['last_patner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'human', type_='foreignkey')
    op.drop_column('human', 'last_patner')
    # ### end Alembic commands ###
