"""partner upd3

Revision ID: cf38e5cbadec
Revises: f4ba2718aa1c
Create Date: 2025-06-08 17:16:48.099874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf38e5cbadec'
down_revision: Union[str, None] = 'f4ba2718aa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('human_father_id_fkey'), 'human', type_='foreignkey')
    op.drop_constraint(op.f('human_last_partner_fkey'), 'human', type_='foreignkey')
    op.create_foreign_key(None, 'human', 'human', ['last_partner'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'human', 'human', ['father_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'human', type_='foreignkey')
    op.drop_constraint(None, 'human', type_='foreignkey')
    op.create_foreign_key(op.f('human_last_partner_fkey'), 'human', 'human', ['last_partner'], ['id'])
    op.create_foreign_key(op.f('human_father_id_fkey'), 'human', 'human', ['father_id'], ['id'])
    # ### end Alembic commands ###
