"""partner upd

Revision ID: f4ba2718aa1c
Revises: 4786ee9c3974
Create Date: 2025-06-08 17:15:10.169275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ba2718aa1c'
down_revision: Union[str, None] = '4786ee9c3974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('human_mother_id_fkey'), 'human', type_='foreignkey')
    op.create_foreign_key(None, 'human', 'human', ['mother_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'human', type_='foreignkey')
    op.create_foreign_key(op.f('human_mother_id_fkey'), 'human', 'human', ['mother_id'], ['id'])
    # ### end Alembic commands ###
